# Generated by Django 2.1.5 on 2019-01-27 14:06

import Cookbook.defines
import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cookbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='菜谱名称')),
                ('url_video', models.URLField(default='', verbose_name='菜谱视频')),
                ('url_cover_image', models.URLField(default='', verbose_name='封面图')),
            ],
            options={
                'verbose_name': '菜谱',
                'verbose_name_plural': '菜谱',
            },
        ),
        migrations.CreateModel(
            name='CookbookTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='菜谱标签')),
                ('priority', models.SmallIntegerField(default=0, verbose_name='优先级')),
                ('cookbook_sum', models.IntegerField(default=0, verbose_name='菜谱数量')),
            ],
            options={
                'verbose_name': '菜谱标签',
                'verbose_name_plural': '菜谱标签',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='原料名称')),
                ('amount', models.CharField(default='', max_length=255, verbose_name='原料数量')),
                ('detail', models.TextField(default='', verbose_name='原料详情')),
                ('type', models.SmallIntegerField(choices=[(Cookbook.defines.MaterialType(1), '食材'), (Cookbook.defines.MaterialType(2), '调料'), (Cookbook.defines.MaterialType(3), '工具')], verbose_name='原料类型')),
                ('priority', models.SmallIntegerField(default=0, verbose_name='优先级')),
                ('img_url', models.URLField(default='', verbose_name='原料图片')),
            ],
            options={
                'verbose_name': '菜谱原料',
                'verbose_name_plural': '菜谱原料',
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='步骤名称')),
                ('detail', models.TextField(default='', verbose_name='步骤详情')),
                ('priority', models.SmallIntegerField(default=0, verbose_name='优先级')),
                ('img_url', models.URLField(default='', verbose_name='步骤图片')),
                ('duration', models.DurationField(default=datetime.timedelta(0), verbose_name='步骤持续时间')),
                ('cookbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_set', to='Cookbook.Cookbook')),
            ],
            options={
                'verbose_name': '菜谱步骤',
                'verbose_name_plural': '菜谱步骤',
            },
        ),
        migrations.CreateModel(
            name='TagCookbookRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField(default=0, verbose_name='点赞数量')),
                ('unlike', models.IntegerField(default=0, verbose_name='踩数量')),
                ('cookbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cookbook.Cookbook')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cookbook.CookbookTag')),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_set', to='Cookbook.Step'),
        ),
        migrations.AddField(
            model_name='cookbook',
            name='tag_set',
            field=models.ManyToManyField(blank=True, related_name='cookbook_set', through='Cookbook.TagCookbookRelationship', to='Cookbook.CookbookTag'),
        ),
    ]
