# Generated by Django 2.1.5 on 2019-02-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cookbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookbook',
            name='checked',
            field=models.BooleanField(default=False, verbose_name='检查过 可展示'),
        ),
    ]
